import { Empleado } from "./empleado.js";
import{ Persona } from "./persona.js";
import { PersonaServicio } from "./personaservicio.js";
import { Estudiante } from "./estudiante.js";
import { Profesor } from "./profesor.js";
const persona = new Persona("David", "Fernandez", "1315242592", "Soltero");
persona.cambiarEstadoCivil("soltero");
const empleado = new Empleado("David", "Fernandez", "1315242592", "Soltero", 2010, 444);
empleado.despacho(444);
const estudiante = new Estudiante("David", "Fernandez", "1315242592", "Soltero","cinco","seis");
estudiante.nuevaMatricula("Octavo")
const personaservicio = new PersonaServicio("David", "Fernandez", "1315242592", "Soltero", 2010, 444,"ocho");
personaservicio.trasladoSeccion("cinco");
const profesor = new Profesor("David", "Fernandez", "1315242592", "Soltero", 2010, 444,"estadistica");
profesor.cambioCurso("matematicas");
console.log(persona);
console.log(empleado);
console.log(estudiante);
console.log(personaservicio);
console.log(profesor);