"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var empleado_js_1 = require("./empleado.js");
var persona_js_1 = require("./persona.js");
var personaservicio_js_1 = require("./personaservicio.js");
var estudiante_js_1 = require("./estudiante.js");
var profesor_js_1 = require("./profesor.js");
var persona = new persona_js_1.Persona("David", "Fernandez", "1344842930", "Soltero");
persona.cambiarEstadoCivil("soltero");
var empleado = new empleado_js_1.Empleado("David", "Fernandez", "1344842930", "Soltero", 2010, 6078);
empleado.despacho(7777);
var estudiante = new estudiante_js_1.Estudiante("David", "Fernandez", "1344842930", "Soltero", "cinco", "seis");
estudiante.nuevaMatricula("Octavo");
var personaservicio = new personaservicio_js_1.PersonaServicio("David", "Fernandez", "1344842930", "Soltero", 2010, 6078, "ocho");
personaservicio.trasladoSeccion("cinco");
var profesor = new profesor_js_1.Profesor("David", "Fernandez", "1344842930", "Soltero", 2010, 6078, "estadistica");
profesor.cambioCurso("matematicas");
console.log(persona);
console.log(empleado);
console.log(estudiante);
console.log(personaservicio);
console.log(profesor);
